# Generated by Django 3.2.7 on 2021-09-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Conversation',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='conversation'),
            preserve_default=False,
        ),
    ]
