# Generated by Django 3.2.7 on 2021-09-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210918_1352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='Conversation',
        ),
    ]
