# Generated by Django 3.2.7 on 2021-09-19 06:30

import chat.utils.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=chat.utils.functions.rename_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'mkv', 'mp4', 'flv', 'avi', 'png', 'jpeg'])], verbose_name='media'),
        ),
    ]
