# Generated by Django 3.2.7 on 2021-09-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_end', to=settings.AUTH_USER_MODEL, verbose_name='end user'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='start_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_start', to=settings.AUTH_USER_MODEL, verbose_name='start user'),
        ),
    ]
